version: "3.7"

services:
  lrtzc-casandra:
    container_name: lrtzc-cassandra
    image: cassandra:3.11
    ports:
      - "9042:9042"
    networks:
      - bclannet-it

networks:
  bclannet-it:
    name: bclannet-it
