server:
  port: 8001
  servlet:
    context-path: /trace

cassandra:
  contact-points: localhost





#      spring.data.cassandra.cluster-name= # Name of the Cassandra cluster.
#      spring.data.cassandra.compression= # Compression supported by the Cassandra binary protocol.
#      spring.data.cassandra.connect-timeout-millis= # Socket option: connection time out.
#      spring.data.cassandra.consistency-level= # Queries consistency level.
#      spring.data.cassandra.contact-points=localhost # Comma-separated list of cluster node addresses.
#      spring.data.cassandra.fetch-size= # Queries default fetch size.
#      spring.data.cassandra.keyspace-name= # Keyspace name to use.
#      spring.data.cassandra.load-balancing-policy= # Class name of the load balancing policy.
#      spring.data.cassandra.port= # Port of the Cassandra server.
#      spring.data.cassandra.password= # Login password of the server.
#      spring.data.cassandra.read-timeout-millis= # Socket option: read time out.
#      spring.data.cassandra.reconnection-policy= # Reconnection policy class.
#      spring.data.cassandra.retry-policy= # Class name of the retry policy.
#      spring.data.cassandra.serial-consistency-level= # Queries serial consistency level.
#      spring.data.cassandra.ssl=false # Enable SSL support.
#      spring.data.cassandra.username= # Login user of the server.